---
title: "Project3_API"
author: "Team"
date: "October 18, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r API}
# Introduction
# Passing 107 Skill set to Dice.com API to get the job title, company name

# JSON :

json_file=c(

"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Owning%20Up%20To%20The%20Title",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Problem%20Solving",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Statistics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Machine%20Learning",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Computing",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Wrangling",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Tools%20and%20Technology",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Communication",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Business%20Acumen",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Rock%20Stars",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Other%20Scientific%20Disciplines",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Statistics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Computer%20Science",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Software%20Engineering",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Mathematics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=The%20Blank%20Canvas",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Education",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Intellectual%20Curiosity",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Domain%20Knowledge",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Communication%20Skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Career%20Mapping",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Goals",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Coding%20Skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Mining%20Skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Big%20Data%20Processing%20Platforms",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Hadoop",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Spark",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Flink",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Structured%20Data%20(SQL)",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Unstructured%20Data%20(3-5%20top%20NoSQL%20DBs)",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Knowledge",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Open%20Source%20data%20science%20tools",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Exposure",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Writing%20modular",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=reusable%20code",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Documentation",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=commenting",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Version%20control",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Testing",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Logging",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=understand%20the%20business%20and%20the%20problem",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Understanding%20the%20data",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=SQL%20skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Basic%20math%20skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Slightly%20more%20advanced%20math%20concepts",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Advanced%20Analysis",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Math",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Stats",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Pattern%20Recognition",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Learning",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Uncertainty",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Computer%20Systems",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Advanced%20Computing",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=High%20Performance%20Computing",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Mining",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Bases",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Engineering",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Warehousing.",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Basic%20CS",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Software%20Development",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Tools",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Engineering",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Distributed%20Computing",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Scientific%20Training",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Mathematics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Modeling",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Theory",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Machine%20Learning",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Business%20Analytics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Graph%20Mining",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Network%20Intelligence",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Text%20Mining",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Information%20Retrieval",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Visualization",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Finance",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Consumer%20Internet",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Oil%20and%20Gas",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Bioinformatics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Physics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Advertising",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Education",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=SAS",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Python%20Coding",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Hadoop%20Platform",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=SQL%20Database",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Coding",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Unstructured%20data",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Intellectual%20curiosity",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Business%20acumen",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Communication%20skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=SQL",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Visualization",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Communication%20Skills",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Hadoop",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Spark",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Python",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Statistics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Creativity",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Python",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Machine%20Learning",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=R%20Language",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Big%20Data",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Statistics",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Data%20Mining",
"http://service.dice.com/api/rest/jobsearch/v1/simple.json?skill=Java"
)

length(json_file)

list.of.packages <- c("XML","RCurl","jsonlite", "methods")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(XML)
library(RCurl)
library(jsonlite)
library("methods")

# Read  records from the JSON and export to CSV
for(i in 1 : length(json_file)){
  
  jsondoc <- fromJSON(txt=json_file[i])
  
  Report=paste("Count: ", jsondoc$count, " ", json_file[i])
  
  write.table(Report, file = "/Users/fionaho/Desktop/API_Count.csv", append = TRUE, quote = TRUE, sep = " ",
            eol = "\n", na = "NA", dec = ".", row.names = TRUE,
            col.names = TRUE, qmethod = c("escape", "double"),
            fileEncoding = "")

  write.table(jsondoc, file = "/Users/fionaho/Desktop/API_Job.csv", append = TRUE, quote = TRUE, sep = " ",
            eol = "\n", na = "NA", dec = ".", row.names = TRUE,
            col.names = TRUE, qmethod = c("escape", "double"),
            fileEncoding = "")
  print(jsondoc)
}
```

